### ISSUE TITLE
Some Code Review

### ISSUE THREAD

**Issue by xenlo** [PiDroid-B/ansible-copydata#3]
As discus on IRC, here are some comments I had after reading your role. Please note that I didn't pretend to know all the best practices. It's just some recommendations based on my experience and my personal preferences:

- [`tasks/main.yml` L1](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L1) - The TODOs come inside the yaml, so after `---`
- [`tasks/main.yml` L1](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L1) - Create one issue for each TODO and FIXME and put the issue ID in the comment.
- [`tasks/main.yml` L2](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L2) - Either you put space befor the ':' or you don't but be consistant.
- [`tasks/main.yml` L12](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L12) - You cloud drop the line become false, it's the default value.
- [`tasks/main.yml` L44](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L44) - You should use `loop` instead of `with_items`.
- [`tasks/main.yml` L47](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L47) - Remove the `|default()` those are useless. you already define the var in `defaults/main.yml`.
- [`tasks/main.yml` L49](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L49) - Even your include tasks should have a `name:`.
- [`tasks/main.yml` L58](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L58) - Clean up commented test code…
- [`tasks/remove_other_files.yml` L1](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/remove_other_files.yml#L1) - A YAML file always start with `---`. This is also valid for `append_file.yml`, `copy_file.yml` and `check_vars.yml`.
- [`meta/main.yml` L10](https://github.com/PiDroid-B/ansible-copydata/blob/master/meta/main.yml#L10) - Clean up all comments that were there to help you to fill the file.
- Globally: I'm not a huge fan of prefix all tasks name with the tasks file name. I was doing that in the begining, but now that I'm use to follow Ansible output, I think that it makes more difficult to read. And it also allow you te remove the ':' that you have in all names and which is not a good idea in YAML.

**Comment by PiDroid-B** [comment]
A lot of thank's for your feedback

>     * [`tasks/main.yml` L1](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L1) - The TODOs come inside the yaml, so after `---`
>     * [`tasks/main.yml` L1](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L1) - Create one issue for each TODO and FIXME and put the issue ID in the comment.
>     * [`tasks/main.yml` L2](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L2) - Either you put space befor the ':' or you don't but be consistant.
:+1:
Removed because obsolated but i know it for the next times 

>     * [`tasks/main.yml` L12](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L12) - You cloud drop the line become false, it's the default value.
For those cases, it forced false to the `locahost` (delegate_to)... But it doesn't work. 

I try fix it but no good result... **PENDING**

 :warning: **===> Question :** How to force `become: False` for `delegate_to: "localhost"` ?
I search about that to solve it for the next commit.

I improve the test about that : 
- default (copy) Step 6 ansible_become:True
- default_append Step 6 ansible_become:True
- default_append_reverse Step 6 ansible_become:True

>     * [`tasks/main.yml` L44](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L44) - You should use `loop` instead of `with_items`.
:+1:

>     * [`tasks/main.yml` L47](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L47) - Remove the `|default()` those are useless. you already define the var in `defaults/main.yml`.
:+1:

>     * [`tasks/main.yml` L49](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L49) - Even your include tasks should have a `name:`.
:+1:

>     * [`tasks/main.yml` L58](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L58) - Clean up commented test code…
Ouupppss... Done! :+1:

>     * [`tasks/remove_other_files.yml` L1](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/remove_other_files.yml#L1) - A YAML file always start with `---`. This is also valid for `append_file.yml`, `copy_file.yml` and `check_vars.yml`.
:+1:

>     * [`meta/main.yml` L10](https://github.com/PiDroid-B/ansible-copydata/blob/master/meta/main.yml#L10) - Clean up all comments that were there to help you to fill the file.

Kept only comment about license because i didn't understand the according documentation (GPLv3+ required or some other constraint ?)
**PENDING**

>     * Globally: I'm not a huge fan of prefix all tasks name with the tasks file name. I was doing that in the begining, but now that I'm use to follow Ansible output, I think that it makes more difficult to read. And it also allow you te remove the ':' that you have in all names and which is not a good idea in YAML.

Ok i do that ! 
I think i have to improve how to follow output and/or debug from output result (i take all suggest)

Thank's again for your help :+1:

**Comment by PiDroid-B** [comment]
> > ```
> > * [`tasks/main.yml` L12](https://github.com/PiDroid-B/ansible-copydata/blob/master/tasks/main.yml#L12) - You cloud drop the line become false, it's the default value.
> > ```
> 
> For those cases, it forced false to the `locahost` (delegate_to)... But it doesn't work.
> 
> I try fix it but no good result... **PENDING**
> 
> warning **===> Question :** How to force `become: False` for `delegate_to: "localhost"` ?
> I search about that to solve it for the next commit.
> 
> I improve the test about that :
> 
>     * default (copy) Step 6 ansible_become:True
> 
>     * default_append Step 6 ansible_become:True
> 
>     * default_append_reverse Step 6 ansible_become:True

Fix : adc61e60657dcd28ef9c94ce64f745253e3bfc34

migration of "delegate_to" task into a subtask solve the ansible_become problem

**Comment by PiDroid-B** [comment]
License ok.
All tasks done

**Comment by PiDroid-B** [comment]
Merged !
Thank's a lot !
